# -*- coding: utf-8 -*-
# Deployment settings for Magic Score Keeper.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/6.1/s3e/makefile_builder/mkb.py', 'c:/Users/Denny/Documents/Magic Score Keeper/Magic Score Keeper.mkb', '--deploy-only']
mkb = 'c:/Users/Denny/Documents/Magic Score Keeper/Magic Score Keeper.mkb'
mkf = ['c:\\marmalade\\6.1\\modules\\iwui\\iwui.mkf', 'c:\\marmalade\\6.1\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\6.1\\modules\\iwutil\\iwutil.mkf', u'c:\\users\\denny\\appdata\\roaming\\marmalade\\packages\\6.1.1\\libjpeg_6b\\libjpeg.mkf', u'c:\\users\\denny\\appdata\\roaming\\marmalade\\packages\\6.1.1\\libpng_1.2.34\\libpng.mkf', u'c:\\users\\denny\\appdata\\roaming\\marmalade\\packages\\6.1.1\\zlib_1.2.4\\zlib.mkf', 'c:\\marmalade\\6.1\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\6.1\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\6.1\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\6.1\\modules\\iwgxfont\\iwgxfont.mkf', u'c:\\users\\denny\\appdata\\roaming\\marmalade\\packages\\6.1.1\\tiniconv_1.0.1\\tiniconv.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/Denny/Documents/Magic Score Keeper/data-ram/data-gles1/ui.group.bin', 'ui.group.bin', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'Magic Score Keeper'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'Magic Score Keeper'
    long_caption = 'Magic Score Keeper'
    version = [0, 0, 1]
    config = ['c:/Users/Denny/Documents/Magic Score Keeper/data/app.icf']
    data_dir = 'c:/Users/Denny/Documents/Magic Score Keeper/data'
    iphone_link_lib = []
    linux_ext_lib = []
    iphone_link_libdir = []
    iphone_link_opts = []
    osx_ext_dll = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    android_extra_application_manifest = []
    win32_ext_dll = []
    android_so = []
    iphone_link_libs = []
    target = {
         'arm' : {
                   'debug'   : r'c:/Users/Denny/Documents/Magic Score Keeper/build_magic score keeper_vc9/Debug_Magic Score Keeper_VC9_arm/Magic Score Keeper.s3e',
                   'release' : r'c:/Users/Denny/Documents/Magic Score Keeper/build_magic score keeper_vc9/Release_Magic Score Keeper_VC9_arm/Magic Score Keeper.s3e',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/Denny/Documents/Magic Score Keeper/build_magic score keeper_vc9/Debug_Magic Score Keeper_VC9_gcc_mips/Magic Score Keeper.so',
                   'release' : r'c:/Users/Denny/Documents/Magic Score Keeper/build_magic score keeper_vc9/Release_Magic Score Keeper_VC9_gcc_mips/Magic Score Keeper.so',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/Denny/Documents/Magic Score Keeper/build_magic score keeper_vc9/Debug_Magic Score Keeper_VC9_x86/Magic Score Keeper.s86',
                   'release' : r'c:/Users/Denny/Documents/Magic Score Keeper/build_magic score keeper_vc9/Release_Magic Score Keeper_VC9_x86/Magic Score Keeper.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/Denny/Documents/Magic Score Keeper/build_magic score keeper_vc9/Debug_Magic Score Keeper_VC9_gcc_arm/Magic Score Keeper.s3e',
                   'release' : r'c:/Users/Denny/Documents/Magic Score Keeper/build_magic score keeper_vc9/Release_Magic Score Keeper_VC9_gcc_arm/Magic Score Keeper.s3e',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
